### ISSUE TITLE
Furnichecker error

### ISSUE THREAD

**Issue by MiClobiMC** [xAstroBoy/RetroFun#3]
Furnichecker has an error when I enter a room, the tanji stops working. I would like furnichecker not to be activated automatically as I will not use it.

**Comment by ghost** [comment]
If you show me the error, i could patch it.

**Comment by MiClobiMC** [comment]
This is the error https://i.imgur.com/jFnzgj4.jpg

**Comment by ghost** [comment]
Usually the furnichecker just logs the furnis, and it won't scan until  you put some files on it.
What retro is that?

**Comment by MiClobiMC** [comment]
Is hartico.com. Maybe I have installed the retrofun wrong. Besides the module, is there anything else to install?

**Comment by MiClobiMC** [comment]
The same error above continues to occur

**Comment by ghost** [comment]
It has been patched, removing hartico from the furnievent parser.

**Comment by ghost** [comment]
If i figure a way to get the parser to not throw the massive error , i might get it unblocked for hartico and other retroservers with the same issue
